### ISSUE TITLE
Wrong link (link itself isn't working on your server)

### ISSUE THREAD

**Issue by GalGreenfield** [STEMinds/Eduponics-Mini#2]
I found 2 bugs regarding your server, leaving it here as the bug I found is for a specific link given here and I don't know about other bugs regarding links:
 1. The kit's introduction documentation - the URL [https://wiki.steminds.com/kits/eduponics_mini/introduction](https://wiki.steminds.com/kits/eduponics_mini/introduction) works while [https://wiki.steminds.com/kits/eduponics_mini/introduction/](https://wiki.steminds.com/kits/eduponics_mini/introduction/) doesn't. I suppose your server doesn't clean the `/` that out of the URL.
 2. Your repo for the kit contains the wrong link non-working link with the `/` so it's not possible to click the link here (in the readme file) to access the documentation.

**Comment by Zontex** [comment]
> I found 2 bugs regarding your server, leaving it here as the bug I found is for a specific link given here and I don't know about other bugs regarding links:
> 
> 1. The kit's introduction documentation - the URL https://wiki.steminds.com/kits/eduponics_mini/introduction works while https://wiki.steminds.com/kits/eduponics_mini/introduction/ doesn't. I suppose your server doesn't clean the `/` that out of the URL.
> 2. Your repo for the kit contains the wrong link non-working link with the `/` so it's not possible to click the link here (in the readme file) to access the documentation.

Hi, thanks for letting me know - the link was fixed in the README.md file, the wiki indeed doesn't work with /, this is added to future TODO list as well

**Comment by Zontex** [comment]
@GalGreenfield a year late but this issue fixed by re-creating the entire documentation to be more SEO friendly. all links from wiki.steminds.com will now be redirected to docs.steminds.com
